/*
   This file is generated by hostbuild 
   (DynamicVersionInfo in modules_prepare).
*/
#ifndef DYNAMICVERSIONINFO_H
#define DYNAMICVERSIONINFO_H

#define VERSION_YEAR                    "2011"

/* Customer to edit below line to reflect desired version number */
#define VERSION_APP_FULL_NUMERIC        2,4,0,0

/* Customer to edit below line to reflect desired version number */
#define VERSION_APP_FULL_STR            "2.4.0.0"

#define VERSION_BLUESUITE_STR           "2.4"

#define VERSION_PRODUCT                 "CSR Host Tools"

#define RELEASE                         1
#define BETA                            2
#define BETA_MAINLINE                   3
#define RC                              4
#define TEST                            5
#define CHARACTERISATION                6
#define UNCONTROLLED_BUILDSYSTEM        100
#define UNCONTROLLED_RAW                101

#if 126
#if RELEASE == RELEASE
#define VERSION_SPECIAL_BUILD           ""
#else
#define VERSION_SPECIAL_BUILD           "Release Build"
#endif
#else
/* Customer to edit below line to be: #define VERSION_SPECIAL_BUILD           "" */
#define VERSION_SPECIAL_BUILD           "Release Build - 126"
#endif

#undef RELEASE
#undef BETA
#undef BETA_MAINLINE
#undef RC
#undef TEST
#undef CHARACTERISATION
#undef UNCONTROLLED_BUILDSYSTEM
#undef UNCONTROLLED_RAW

#define VERSION_APP_MAJOR           2
#define VERSION_APP_MINOR           4
#define VERSION_APP_REVISION        0
#define VERSION_APP_BUILD           0


#endif /*DYNAMICVERSIONINFO_H*/
