/*******************************************************************************

               (c) Cambridge Silicon Radio Limited 2009

               All rights reserved and confidential information of CSR

REVISION:      $Revision$
*******************************************************************************/
/******************************************************************************/
/* This file was autogenerated (using genApi.py) from:                        */
/*     c:\work_bluesuite_2_4\p4\bc\bluesuite_2_4\devHost\btcli\\..\..\interface\host\bccmd\dspmanager_status.xml*/
/* Generated on 2011-06-01                                                    */
/******************************************************************************/

#ifndef DSPMANAGER_STATUS_H
#define DSPMANAGER_STATUS_H
enum dspmanager_status
{
  /* Stibbons status codes                                                    */
  DSPMANAGER_STATUS_SUCCESS = 0,
  DSPMANAGER_STATUS_UNKNOWN_CAPABILITY = 1,
  DSPMANAGER_STATUS_INTERNAL_COMMS_ERROR = 2,
  DSPMANAGER_STATUS_NO_FREE_IDENTIFIERS = 3,
  DSPMANAGER_STATUS_OUT_OF_MEMORY = 4,
  DSPMANAGER_STATUS_CANT_LAUNCH_SUBSYSTEM = 5,
  DSPMANAGER_STATUS_INVALID_OPERAND = 6,
  DSPMANAGER_STATUS_INSUFFICIENT_RESOURCE = 7,
  DSPMANAGER_STATUS_ALREADY_CONNECTED = 8,
  DSPMANAGER_STATUS_UNKNOWN_SUBSYSTEM = 9,
  DSPMANAGER_STATUS_COMMAND_SEQUENCE_ERROR = 10,
  DSPMANAGER_STATUS_INTERNAL_BAD_VALUE = 11,
  DSPMANAGER_STATUS_COMMAND_LENGTH_ERROR = 12,
  DSPMANAGER_STATUS_UNKNOWN_SUBCOMMAND = 13,
  /* Baton status codes                                                       */
  DSPMANAGER_STATUS_BAD_OPID = 129,
  DSPMANAGER_STATUS_SOURCE_PORT_IN_USE = 130,
  DSPMANAGER_STATUS_SINK_PORT_IN_USE = 131,
  DSPMANAGER_STATUS_UNKNOWN_PORT_ID = 132,
  DSPMANAGER_STATUS_SOURCE_PORT_NOT_IN_USE = 133,
  DSPMANAGER_STATUS_OPERATOR_CANNOT_CONNECT_WHEN_RUNNING = 134,
  DSPMANAGER_STATUS_WRONG_STATE = 135,
  DSPMANAGER_STATUS_UNKNOWN_ERROR = 136,
  DSPMANAGER_STATUS_OUT_OF_RAM = 137,
  DSPMANAGER_STATUS_SOURCE_PORT_NOT_CONNECTED = 138,
  DSPMANAGER_STATUS_SINK_PORT_NOT_CONNECTED = 139,
  DSPMANAGER_STATUS_UNKNOWN_BCID = 140,
  DSPMANAGER_STATUS_UNKNOWN_OID = 141,
  DSPMANAGER_STATUS_ZERO_LENGTH = 142,
  DSPMANAGER_STATUS_OPERATOR_RUNNING = 143,
  DSPMANAGER_STATUS_DISCONNECT_ERROR = 144,
  DSPMANAGER_STATUS_UNKNOWN_MESSAGE = 145,
  DSPMANAGER_STATUS_UNSUPPORTED_MESSAGE = 146,
  DSPMANAGER_STATUS_OPID_IN_USE = 147,
  DSPMANAGER_STATUS_UNKNOWN_CAP = 148,
  DSPMANAGER_STATUS_PORT_STATE_WRONG = 149,
  DSPMANAGER_STATUS_INVALID_TERMINAL = 150,
  DSPMANAGER_STATUS_INCOMPATIBLE_DATA_TYPES = 151,
  DSPMANAGER_STATUS_STREAM_IN_WRONG_STATE = 152,
  DSPMANAGER_STATUS_INVALID_DATA = 153,
  DSPMANAGER_STATUS_OPERATOR_NOT_CONFIGURED = 154,
  DSPMANAGER_STATUS_INVALID_RESAMPLER_RATE = 155,
  DSPMANAGER_STATUS_UNKNOWN_PROBLEM = 255
};

typedef enum dspmanager_status dspmanager_status;

#endif
