//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PSTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define ID_HELP_FIRMWARE                0x0010
#define IDM_ACCESS_LEVEL                0x0020
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PSTOOL_DIALOG               102
#define IDS_ACCESS_LEVEL                102
#define IDD_PS_INSERT                   103
#define IDD_PSDESCRDLG_DIALOG           104
#define IDD_ACCESSLEVELDLG_DIALOG       105
#define IDD_PSRAWDLG_DIALOG             108
#define IDD_IGNOREALL_DIALOG            109
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   133
#define IDR_ACCEL_PSTOOL                134
#define IDD_CHOOSETRANS                 135
#define IDD_EPS_INSERT                  138
#define IDD_POWER_TABLE_V0_INSERT       139
#define IDC_ED_VAL                      1004
#define IDC_SPIN_VAL                    1005
#define IDC_LIST_KEYS                   1006
#define IDC_COMBO_ENUM                  1007
#define IDC_RAD_ALL                     1008
#define IDC_RAD_DEVELOPER               1009
#define IDC_RAD_USER                    1010
#define IDC_CLOSE                       1011
#define IDC_SET                         1012
#define IDC_READ                        1013
#define IDC_ED_STR                      1014
#define IDC_RESETCLOSE                  1015
#define IDC_GRID_PS                     1017
#define IDC_CAPTION_PRESENT             1018
#define IDC_KEY_LABEL                   1019
#define IDC_BUT_PS_INSERT               1020
#define IDC_BUT_PS_DELETE               1021
#define IDC_ED_GRID_PS                  1022
#define IDC_ED_PS_INTERNAL_PA           1025
#define IDC_ED_PS_EXTERNAL_PA           1026
#define IDC_ED_PS_DBM                   1028
#define IDC_BUT_PS_EDIT                 1029
#define IDC_DESCRIBE                    1030
#define IDC_ED_DESCR                    1031
#define IDC_BUT_RESET                   1032
#define IDC_CB_ACCESS                   1034
#define IDC_ED_ACC_KEY                  1035
#define IDC_BUT_ACCESS                  1036
#define IDC_BUT_DEL_KEY                 1037
#define IDC_EDIT1                       1038
#define IDC_ED_LAP                      1038
#define IDC_ED_PRESKEYS                 1038
#define IDC_EDR_INTERNAL_PA             1038
#define IDC_SPIN1                       1039
#define IDC_SPIN_KEY                    1039
#define IDC_EDIT2                       1040
#define IDC_ED_UAP                      1040
#define IDC_EDR_EXTERNAL_PA             1040
#define IDC_RAD_DEC                     1041
#define IDC_RAD_DEC_KEY                 1041
#define IDC_EDR_MIX_OFFSET              1041
#define IDC_RAD_HEX                     1042
#define IDC_RAD_HEX_KEY                 1042
#define IDC_BUTTON1                     1043
#define IDC_BUT_RECONNECCT              1043
#define IDC_DELETE                      1043
#define IDC_BUTTON2                     1044
#define IDC_RAD_DEC_VAL                 1044
#define IDC_BUT_NOTPRESENT              1044
#define IDC_ED_KEY                      1045
#define IDC_RAD_HEX_VAL                 1046
#define IDC_RAD_STR_VAL                 1047
#define IDC_CB_PORT                     1049
#define IDC_CB_BAUD                     1050
#define IDC_RAD_SPI_BCCMD               1052
#define IDC_RAD_BCSP                    1053
#define IDC_RAD_H4                      1054
#define IDC_RAD_USB                     1055
#define IDC_RAD_H5                      1056
#define IDC_EDIT_FORMAT                 1060
#define IDIGNOREALL                     1062
#define IDC_MESSAGE_TEXT                1063
#define IDC_ABOUT_TITLE                 1064
#define IDC_ABOUT_COPYRIGHT             1065
#define IDC_ABOUT_BUILD                 1066
#define IDC_BAUD_STATIC                 1067
#define IDC_SPI_STOP                    1068
#define IDC_ED_NAP                      1069
#define IDC_STATIC_LAP                  1070
#define IDC_STATIC_UAP                  1071
#define IDC_STATIC_NAP                  1072
#define IDC_STATIC_PRESREL              1074
#define IDC_EDR_CLASS                   1078
#define IDC_EDR_TX_PA_ATTN              1079
#define IDC_EDR_TX_PRE                  1080
#define IDC_OUTPUT_DBM                  1081
#define IDC_BR_INTERNAL_PA              1082
#define IDC_BR_EXTERNAL_PA              1083
#define IDC_NO_BR                       1083
#define IDC_PA_CTRL_BITS                1084
#define IDC_BR_MIX_OFFSET               1084
#define IDC_ED_FILTER                   1085
#define IDC_EDC_NO_BR                   1085
#define IDC_EDR_NO_BR                   1085
#define IDC_BR_TX_PA_ATTN               1086
#define IDC_CACHE                       1086
#define IDC_EDR_MIX_LEVEL               1087
#define IDC_BR_MIX_LEVEL                1088
#define ID_FILE_RESTOREFROMFILE         32771
#define ID_FILE_SAVETOFILE              32772
#define ID_FILE_EXIT                    32773
#define ID_KEY_READ                     32774
#define ID_KEY_SET                      32775
#define ID_KEY_DELETE                   32776
#define ID_FACTORY_FACTORYSET           32777
#define ID_FACTORY_FACTORYRESTORE       32778
#define ID_FACTORY_FACTORYRESTOREALL    32779
#define ID_HELP_ABOUT                   32780
#define ID_KEY_DESCRIBE                 32781
#define ID_HELP_DESCRIBEKEY             32782
#define ID_FILE_ACCESS                  32783
#define ID_VIEW_SORTBYNAME              32784
#define ID_VIEW_SORTBYORDINAL           32785
#define ID_VIEW_FRIENDLYNAMES           32786
#define ID_VIEW_PROGRAMMERIDS           32787
#define ID_KEY_EDITRAW                  32790
#define IDA_ACCESS_ALL                  32791
#define IDA_ACCESS_DEV                  32792
#define IDA_ACCESS_USER                 32793
#define ID_FILE_MERGE                   32794
#define ID_FILE_RUNQUERY                32795
#define ID_FILE_DUMP                    32796
#define ID_STORES_ALL                   32798
#define ID_STORES_IMPLEMENTATION        32799
#define ID_STORES_ROMONLY               32800
#define ID_STORES_RAMONLY               32801
#define ID_STORES_FACTORYONLY           32802
#define ID_STORES_NOTRAM                32803
#define ID_BOOTMODE_NONE                32804
#define ID_BOOTMODE_0                   32806
#define ID_BOOTMODE_1                   32807
#define ID_BOOTMODE_2                   32808
#define ID_BOOTMODE_3                   32809
#define ID_BOOTMODE_4                   32810
#define ID_BOOTMODE_5                   32811
#define ID_BOOTMODE_6                   32812
#define ID_BOOTMODE_7                   32813
#define ID_BOOTMODE_DELETE_KEY          32815
#define ID_BOOTMODE_SHOWONLYOVERRIDES   32821
#define ID_VIEW_SHOWONLYSET             32823
#define ID_KEY_CANNED_MIN               35100
#define ID_KEY_CANNED_MAX               35164

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
