////////////////////////////////////////////////////////////////////////////////
//
//  WARNING THIS IS AN AUTOGENERATED FILE DEFINING A BLUECORE-FRIENDY PROTOCOL
//
////////////////////////////////////////////////////////////////////////////////

#include "bcflayout.h"


enum {
	OFFSET_START(ATT_CONNECT_CFM_T)
	OFFSET_uint16(ATT_CONNECT_CFM_T_type),
	OFFSET_uint16(ATT_CONNECT_CFM_T_phandle),
	OFFSET_BluetoothDeviceAddressWithType(ATT_CONNECT_CFM_T_addrt),
	OFFSET_uint16(ATT_CONNECT_CFM_T_flags),
	OFFSET_uint16(ATT_CONNECT_CFM_T_cid),
	OFFSET_uint16(ATT_CONNECT_CFM_T_mtu),
	OFFSET_l2ca_conn_result_t(ATT_CONNECT_CFM_T_result),
	ATT_CONNECT_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_READ_BLOB_REQ_T)
	OFFSET_uint16(ATT_READ_BLOB_REQ_T_type),
	OFFSET_uint16(ATT_READ_BLOB_REQ_T_phandle),
	OFFSET_uint16(ATT_READ_BLOB_REQ_T_cid),
	OFFSET_uint16(ATT_READ_BLOB_REQ_T_handle),
	OFFSET_uint16(ATT_READ_BLOB_REQ_T_offset),
	ATT_READ_BLOB_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_EXCHANGE_MTU_RSP_T)
	OFFSET_uint16(ATT_EXCHANGE_MTU_RSP_T_type),
	OFFSET_uint16(ATT_EXCHANGE_MTU_RSP_T_phandle),
	OFFSET_uint16(ATT_EXCHANGE_MTU_RSP_T_cid),
	OFFSET_uint16(ATT_EXCHANGE_MTU_RSP_T_server_mtu),
	ATT_EXCHANGE_MTU_RSP_T_pduSize
} ;

enum {
	OFFSET_START(ATT_DISCONNECT_IND_T)
	OFFSET_uint16(ATT_DISCONNECT_IND_T_type),
	OFFSET_uint16(ATT_DISCONNECT_IND_T_phandle),
	OFFSET_uint16(ATT_DISCONNECT_IND_T_cid),
	OFFSET_l2ca_disc_result_t(ATT_DISCONNECT_IND_T_reason),
	ATT_DISCONNECT_IND_T_pduSize
} ;

enum {
	OFFSET_START(ATT_UNREGISTER_CFM_T)
	OFFSET_uint16(ATT_UNREGISTER_CFM_T_type),
	OFFSET_uint16(ATT_UNREGISTER_CFM_T_phandle),
	OFFSET_uint16(ATT_UNREGISTER_CFM_T_result),
	ATT_UNREGISTER_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_EXECUTE_WRITE_REQ_T)
	OFFSET_uint16(ATT_EXECUTE_WRITE_REQ_T_type),
	OFFSET_uint16(ATT_EXECUTE_WRITE_REQ_T_phandle),
	OFFSET_uint16(ATT_EXECUTE_WRITE_REQ_T_cid),
	OFFSET_uint16(ATT_EXECUTE_WRITE_REQ_T_flags),
	ATT_EXECUTE_WRITE_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_DISCONNECT_REQ_T)
	OFFSET_uint16(ATT_DISCONNECT_REQ_T_type),
	OFFSET_uint16(ATT_DISCONNECT_REQ_T_phandle),
	OFFSET_uint16(ATT_DISCONNECT_REQ_T_cid),
	ATT_DISCONNECT_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_REGISTER_CFM_T)
	OFFSET_uint16(ATT_REGISTER_CFM_T_type),
	OFFSET_uint16(ATT_REGISTER_CFM_T_phandle),
	OFFSET_uint16(ATT_REGISTER_CFM_T_result),
	ATT_REGISTER_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_FIND_BY_TYPE_VALUE_CFM_T)
	OFFSET_uint16(ATT_FIND_BY_TYPE_VALUE_CFM_T_type),
	OFFSET_uint16(ATT_FIND_BY_TYPE_VALUE_CFM_T_phandle),
	OFFSET_uint16(ATT_FIND_BY_TYPE_VALUE_CFM_T_cid),
	OFFSET_uint16(ATT_FIND_BY_TYPE_VALUE_CFM_T_handle),
	OFFSET_uint16(ATT_FIND_BY_TYPE_VALUE_CFM_T_end),
	OFFSET_uint16(ATT_FIND_BY_TYPE_VALUE_CFM_T_result),
	ATT_FIND_BY_TYPE_VALUE_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_EXCHANGE_MTU_IND_T)
	OFFSET_uint16(ATT_EXCHANGE_MTU_IND_T_type),
	OFFSET_uint16(ATT_EXCHANGE_MTU_IND_T_phandle),
	OFFSET_uint16(ATT_EXCHANGE_MTU_IND_T_cid),
	OFFSET_uint16(ATT_EXCHANGE_MTU_IND_T_client_mtu),
	ATT_EXCHANGE_MTU_IND_T_pduSize
} ;

enum {
	OFFSET_START(ATT_EXCHANGE_MTU_REQ_T)
	OFFSET_uint16(ATT_EXCHANGE_MTU_REQ_T_type),
	OFFSET_uint16(ATT_EXCHANGE_MTU_REQ_T_phandle),
	OFFSET_uint16(ATT_EXCHANGE_MTU_REQ_T_cid),
	OFFSET_uint16(ATT_EXCHANGE_MTU_REQ_T_mtu),
	ATT_EXCHANGE_MTU_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_CONNECT_IND_T)
	OFFSET_uint16(ATT_CONNECT_IND_T_type),
	OFFSET_uint16(ATT_CONNECT_IND_T_phandle),
	OFFSET_BluetoothDeviceAddressWithType(ATT_CONNECT_IND_T_addrt),
	OFFSET_uint16(ATT_CONNECT_IND_T_flags),
	OFFSET_uint16(ATT_CONNECT_IND_T_mtu),
	OFFSET_uint16(ATT_CONNECT_IND_T_cid),
	ATT_CONNECT_IND_T_pduSize
} ;

enum {
	OFFSET_START(ATT_READ_REQ_T)
	OFFSET_uint16(ATT_READ_REQ_T_type),
	OFFSET_uint16(ATT_READ_REQ_T_phandle),
	OFFSET_uint16(ATT_READ_REQ_T_cid),
	OFFSET_uint16(ATT_READ_REQ_T_handle),
	ATT_READ_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_EXECUTE_WRITE_CFM_T)
	OFFSET_uint16(ATT_EXECUTE_WRITE_CFM_T_type),
	OFFSET_uint16(ATT_EXECUTE_WRITE_CFM_T_phandle),
	OFFSET_uint16(ATT_EXECUTE_WRITE_CFM_T_cid),
	OFFSET_uint16(ATT_EXECUTE_WRITE_CFM_T_handle),
	OFFSET_uint16(ATT_EXECUTE_WRITE_CFM_T_result),
	ATT_EXECUTE_WRITE_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_HANDLE_VALUE_CFM_T)
	OFFSET_uint16(ATT_HANDLE_VALUE_CFM_T_type),
	OFFSET_uint16(ATT_HANDLE_VALUE_CFM_T_phandle),
	OFFSET_uint16(ATT_HANDLE_VALUE_CFM_T_cid),
	OFFSET_uint16(ATT_HANDLE_VALUE_CFM_T_result),
	ATT_HANDLE_VALUE_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_CONNECT_REQ_T)
	OFFSET_uint16(ATT_CONNECT_REQ_T_type),
	OFFSET_uint16(ATT_CONNECT_REQ_T_phandle),
	OFFSET_BluetoothDeviceAddressWithType(ATT_CONNECT_REQ_T_addrt),
	OFFSET_uint16(ATT_CONNECT_REQ_T_flags),
	ATT_CONNECT_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_FIND_INFO_REQ_T)
	OFFSET_uint16(ATT_FIND_INFO_REQ_T_type),
	OFFSET_uint16(ATT_FIND_INFO_REQ_T_phandle),
	OFFSET_uint16(ATT_FIND_INFO_REQ_T_cid),
	OFFSET_uint16(ATT_FIND_INFO_REQ_T_start),
	OFFSET_uint16(ATT_FIND_INFO_REQ_T_end),
	ATT_FIND_INFO_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_WRITE_CFM_T)
	OFFSET_uint16(ATT_WRITE_CFM_T_type),
	OFFSET_uint16(ATT_WRITE_CFM_T_phandle),
	OFFSET_uint16(ATT_WRITE_CFM_T_cid),
	OFFSET_uint16(ATT_WRITE_CFM_T_result),
	ATT_WRITE_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_ADD_DB_CFM_T)
	OFFSET_uint16(ATT_ADD_DB_CFM_T_type),
	OFFSET_uint16(ATT_ADD_DB_CFM_T_phandle),
	OFFSET_uint16(ATT_ADD_DB_CFM_T_result),
	ATT_ADD_DB_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_EXCHANGE_MTU_CFM_T)
	OFFSET_uint16(ATT_EXCHANGE_MTU_CFM_T_type),
	OFFSET_uint16(ATT_EXCHANGE_MTU_CFM_T_phandle),
	OFFSET_uint16(ATT_EXCHANGE_MTU_CFM_T_cid),
	OFFSET_uint16(ATT_EXCHANGE_MTU_CFM_T_mtu),
	OFFSET_uint16(ATT_EXCHANGE_MTU_CFM_T_result),
	ATT_EXCHANGE_MTU_CFM_T_pduSize
} ;

enum {
	OFFSET_START(ATT_UNREGISTER_REQ_T)
	OFFSET_uint16(ATT_UNREGISTER_REQ_T_type),
	OFFSET_uint16(ATT_UNREGISTER_REQ_T_phandle),
	ATT_UNREGISTER_REQ_T_pduSize
} ;

enum {
	OFFSET_START(ATT_HANDLE_VALUE_RSP_T)
	OFFSET_uint16(ATT_HANDLE_VALUE_RSP_T_type),
	OFFSET_uint16(ATT_HANDLE_VALUE_RSP_T_phandle),
	OFFSET_uint16(ATT_HANDLE_VALUE_RSP_T_cid),
	ATT_HANDLE_VALUE_RSP_T_pduSize
} ;

enum {
	OFFSET_START(ATT_REGISTER_REQ_T)
	OFFSET_uint16(ATT_REGISTER_REQ_T_type),
	OFFSET_uint16(ATT_REGISTER_REQ_T_phandle),
	ATT_REGISTER_REQ_T_pduSize
} ;
#include "hcipacker/gen_att.h"
 
///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_CONNECT_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_CONNECT_CFM_T_PDU::ATT_CONNECT_CFM_T_PDU()
: ATT_PDU ( ATT_CONNECT_CFM , ATT_CONNECT_CFM_T_pduSize )
{
}

ATT_CONNECT_CFM_T_PDU::ATT_CONNECT_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_CONNECT_CFM_T_PDU::ATT_CONNECT_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_CONNECT_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_CONNECT_CFM_T_phandle );
}

void ATT_CONNECT_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_CONNECT_CFM_T_phandle , value );
}

BluetoothDeviceAddressWithType ATT_CONNECT_CFM_T_PDU::get_addrt() const
{
    return get_BluetoothDeviceAddressWithType ( ATT_CONNECT_CFM_T_addrt );
}

void ATT_CONNECT_CFM_T_PDU::set_addrt( BluetoothDeviceAddressWithType value )
{
    set_BluetoothDeviceAddressWithType ( ATT_CONNECT_CFM_T_addrt , value );
}

uint16 ATT_CONNECT_CFM_T_PDU::get_flags() const
{
    return get_uint16 ( ATT_CONNECT_CFM_T_flags );
}

void ATT_CONNECT_CFM_T_PDU::set_flags( uint16 value )
{
    set_uint16 ( ATT_CONNECT_CFM_T_flags , value );
}

uint16 ATT_CONNECT_CFM_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_CONNECT_CFM_T_cid );
}

void ATT_CONNECT_CFM_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_CONNECT_CFM_T_cid , value );
}

uint16 ATT_CONNECT_CFM_T_PDU::get_mtu() const
{
    return get_uint16 ( ATT_CONNECT_CFM_T_mtu );
}

void ATT_CONNECT_CFM_T_PDU::set_mtu( uint16 value )
{
    set_uint16 ( ATT_CONNECT_CFM_T_mtu , value );
}

l2ca_conn_result_t ATT_CONNECT_CFM_T_PDU::get_result() const
{
    return get_l2ca_conn_result_t ( ATT_CONNECT_CFM_T_result );
}

void ATT_CONNECT_CFM_T_PDU::set_result( l2ca_conn_result_t value )
{
    set_l2ca_conn_result_t ( ATT_CONNECT_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_READ_BLOB_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_READ_BLOB_REQ_T_PDU::ATT_READ_BLOB_REQ_T_PDU()
: ATT_PDU ( ATT_READ_BLOB_REQ , ATT_READ_BLOB_REQ_T_pduSize )
{
}

ATT_READ_BLOB_REQ_T_PDU::ATT_READ_BLOB_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_READ_BLOB_REQ_T_PDU::ATT_READ_BLOB_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_READ_BLOB_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_READ_BLOB_REQ_T_phandle );
}

void ATT_READ_BLOB_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_READ_BLOB_REQ_T_phandle , value );
}

uint16 ATT_READ_BLOB_REQ_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_READ_BLOB_REQ_T_cid );
}

void ATT_READ_BLOB_REQ_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_READ_BLOB_REQ_T_cid , value );
}

uint16 ATT_READ_BLOB_REQ_T_PDU::get_handle() const
{
    return get_uint16 ( ATT_READ_BLOB_REQ_T_handle );
}

void ATT_READ_BLOB_REQ_T_PDU::set_handle( uint16 value )
{
    set_uint16 ( ATT_READ_BLOB_REQ_T_handle , value );
}

uint16 ATT_READ_BLOB_REQ_T_PDU::get_offset() const
{
    return get_uint16 ( ATT_READ_BLOB_REQ_T_offset );
}

void ATT_READ_BLOB_REQ_T_PDU::set_offset( uint16 value )
{
    set_uint16 ( ATT_READ_BLOB_REQ_T_offset , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_EXCHANGE_MTU_RSP_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_EXCHANGE_MTU_RSP_T_PDU::ATT_EXCHANGE_MTU_RSP_T_PDU()
: ATT_PDU ( ATT_EXCHANGE_MTU_RSP , ATT_EXCHANGE_MTU_RSP_T_pduSize )
{
}

ATT_EXCHANGE_MTU_RSP_T_PDU::ATT_EXCHANGE_MTU_RSP_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_EXCHANGE_MTU_RSP_T_PDU::ATT_EXCHANGE_MTU_RSP_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_EXCHANGE_MTU_RSP_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_RSP_T_phandle );
}

void ATT_EXCHANGE_MTU_RSP_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_RSP_T_phandle , value );
}

uint16 ATT_EXCHANGE_MTU_RSP_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_RSP_T_cid );
}

void ATT_EXCHANGE_MTU_RSP_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_RSP_T_cid , value );
}

uint16 ATT_EXCHANGE_MTU_RSP_T_PDU::get_server_mtu() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_RSP_T_server_mtu );
}

void ATT_EXCHANGE_MTU_RSP_T_PDU::set_server_mtu( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_RSP_T_server_mtu , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_DISCONNECT_IND_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_DISCONNECT_IND_T_PDU::ATT_DISCONNECT_IND_T_PDU()
: ATT_PDU ( ATT_DISCONNECT_IND , ATT_DISCONNECT_IND_T_pduSize )
{
}

ATT_DISCONNECT_IND_T_PDU::ATT_DISCONNECT_IND_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_DISCONNECT_IND_T_PDU::ATT_DISCONNECT_IND_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_DISCONNECT_IND_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_DISCONNECT_IND_T_phandle );
}

void ATT_DISCONNECT_IND_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_DISCONNECT_IND_T_phandle , value );
}

uint16 ATT_DISCONNECT_IND_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_DISCONNECT_IND_T_cid );
}

void ATT_DISCONNECT_IND_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_DISCONNECT_IND_T_cid , value );
}

l2ca_disc_result_t ATT_DISCONNECT_IND_T_PDU::get_reason() const
{
    return get_l2ca_disc_result_t ( ATT_DISCONNECT_IND_T_reason );
}

void ATT_DISCONNECT_IND_T_PDU::set_reason( l2ca_disc_result_t value )
{
    set_l2ca_disc_result_t ( ATT_DISCONNECT_IND_T_reason , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_UNREGISTER_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_UNREGISTER_CFM_T_PDU::ATT_UNREGISTER_CFM_T_PDU()
: ATT_PDU ( ATT_UNREGISTER_CFM , ATT_UNREGISTER_CFM_T_pduSize )
{
}

ATT_UNREGISTER_CFM_T_PDU::ATT_UNREGISTER_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_UNREGISTER_CFM_T_PDU::ATT_UNREGISTER_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_UNREGISTER_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_UNREGISTER_CFM_T_phandle );
}

void ATT_UNREGISTER_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_UNREGISTER_CFM_T_phandle , value );
}

uint16 ATT_UNREGISTER_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_UNREGISTER_CFM_T_result );
}

void ATT_UNREGISTER_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_UNREGISTER_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_EXECUTE_WRITE_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_EXECUTE_WRITE_REQ_T_PDU::ATT_EXECUTE_WRITE_REQ_T_PDU()
: ATT_PDU ( ATT_EXECUTE_WRITE_REQ , ATT_EXECUTE_WRITE_REQ_T_pduSize )
{
}

ATT_EXECUTE_WRITE_REQ_T_PDU::ATT_EXECUTE_WRITE_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_EXECUTE_WRITE_REQ_T_PDU::ATT_EXECUTE_WRITE_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_EXECUTE_WRITE_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_EXECUTE_WRITE_REQ_T_phandle );
}

void ATT_EXECUTE_WRITE_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_EXECUTE_WRITE_REQ_T_phandle , value );
}

uint16 ATT_EXECUTE_WRITE_REQ_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_EXECUTE_WRITE_REQ_T_cid );
}

void ATT_EXECUTE_WRITE_REQ_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_EXECUTE_WRITE_REQ_T_cid , value );
}

uint16 ATT_EXECUTE_WRITE_REQ_T_PDU::get_flags() const
{
    return get_uint16 ( ATT_EXECUTE_WRITE_REQ_T_flags );
}

void ATT_EXECUTE_WRITE_REQ_T_PDU::set_flags( uint16 value )
{
    set_uint16 ( ATT_EXECUTE_WRITE_REQ_T_flags , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_DISCONNECT_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_DISCONNECT_REQ_T_PDU::ATT_DISCONNECT_REQ_T_PDU()
: ATT_PDU ( ATT_DISCONNECT_REQ , ATT_DISCONNECT_REQ_T_pduSize )
{
}

ATT_DISCONNECT_REQ_T_PDU::ATT_DISCONNECT_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_DISCONNECT_REQ_T_PDU::ATT_DISCONNECT_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_DISCONNECT_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_DISCONNECT_REQ_T_phandle );
}

void ATT_DISCONNECT_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_DISCONNECT_REQ_T_phandle , value );
}

uint16 ATT_DISCONNECT_REQ_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_DISCONNECT_REQ_T_cid );
}

void ATT_DISCONNECT_REQ_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_DISCONNECT_REQ_T_cid , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_REGISTER_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_REGISTER_CFM_T_PDU::ATT_REGISTER_CFM_T_PDU()
: ATT_PDU ( ATT_REGISTER_CFM , ATT_REGISTER_CFM_T_pduSize )
{
}

ATT_REGISTER_CFM_T_PDU::ATT_REGISTER_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_REGISTER_CFM_T_PDU::ATT_REGISTER_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_REGISTER_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_REGISTER_CFM_T_phandle );
}

void ATT_REGISTER_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_REGISTER_CFM_T_phandle , value );
}

uint16 ATT_REGISTER_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_REGISTER_CFM_T_result );
}

void ATT_REGISTER_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_REGISTER_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU()
: ATT_PDU ( ATT_FIND_BY_TYPE_VALUE_CFM , ATT_FIND_BY_TYPE_VALUE_CFM_T_pduSize )
{
}

ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_phandle );
}

void ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_phandle , value );
}

uint16 ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_cid );
}

void ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_cid , value );
}

uint16 ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::get_handle() const
{
    return get_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_handle );
}

void ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::set_handle( uint16 value )
{
    set_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_handle , value );
}

uint16 ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::get_end() const
{
    return get_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_end );
}

void ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::set_end( uint16 value )
{
    set_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_end , value );
}

uint16 ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_result );
}

void ATT_FIND_BY_TYPE_VALUE_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_FIND_BY_TYPE_VALUE_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_EXCHANGE_MTU_IND_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_EXCHANGE_MTU_IND_T_PDU::ATT_EXCHANGE_MTU_IND_T_PDU()
: ATT_PDU ( ATT_EXCHANGE_MTU_IND , ATT_EXCHANGE_MTU_IND_T_pduSize )
{
}

ATT_EXCHANGE_MTU_IND_T_PDU::ATT_EXCHANGE_MTU_IND_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_EXCHANGE_MTU_IND_T_PDU::ATT_EXCHANGE_MTU_IND_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_EXCHANGE_MTU_IND_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_IND_T_phandle );
}

void ATT_EXCHANGE_MTU_IND_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_IND_T_phandle , value );
}

uint16 ATT_EXCHANGE_MTU_IND_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_IND_T_cid );
}

void ATT_EXCHANGE_MTU_IND_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_IND_T_cid , value );
}

uint16 ATT_EXCHANGE_MTU_IND_T_PDU::get_client_mtu() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_IND_T_client_mtu );
}

void ATT_EXCHANGE_MTU_IND_T_PDU::set_client_mtu( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_IND_T_client_mtu , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_EXCHANGE_MTU_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_EXCHANGE_MTU_REQ_T_PDU::ATT_EXCHANGE_MTU_REQ_T_PDU()
: ATT_PDU ( ATT_EXCHANGE_MTU_REQ , ATT_EXCHANGE_MTU_REQ_T_pduSize )
{
}

ATT_EXCHANGE_MTU_REQ_T_PDU::ATT_EXCHANGE_MTU_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_EXCHANGE_MTU_REQ_T_PDU::ATT_EXCHANGE_MTU_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_EXCHANGE_MTU_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_REQ_T_phandle );
}

void ATT_EXCHANGE_MTU_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_REQ_T_phandle , value );
}

uint16 ATT_EXCHANGE_MTU_REQ_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_REQ_T_cid );
}

void ATT_EXCHANGE_MTU_REQ_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_REQ_T_cid , value );
}

uint16 ATT_EXCHANGE_MTU_REQ_T_PDU::get_mtu() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_REQ_T_mtu );
}

void ATT_EXCHANGE_MTU_REQ_T_PDU::set_mtu( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_REQ_T_mtu , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_CONNECT_IND_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_CONNECT_IND_T_PDU::ATT_CONNECT_IND_T_PDU()
: ATT_PDU ( ATT_CONNECT_IND , ATT_CONNECT_IND_T_pduSize )
{
}

ATT_CONNECT_IND_T_PDU::ATT_CONNECT_IND_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_CONNECT_IND_T_PDU::ATT_CONNECT_IND_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_CONNECT_IND_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_CONNECT_IND_T_phandle );
}

void ATT_CONNECT_IND_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_CONNECT_IND_T_phandle , value );
}

BluetoothDeviceAddressWithType ATT_CONNECT_IND_T_PDU::get_addrt() const
{
    return get_BluetoothDeviceAddressWithType ( ATT_CONNECT_IND_T_addrt );
}

void ATT_CONNECT_IND_T_PDU::set_addrt( BluetoothDeviceAddressWithType value )
{
    set_BluetoothDeviceAddressWithType ( ATT_CONNECT_IND_T_addrt , value );
}

uint16 ATT_CONNECT_IND_T_PDU::get_flags() const
{
    return get_uint16 ( ATT_CONNECT_IND_T_flags );
}

void ATT_CONNECT_IND_T_PDU::set_flags( uint16 value )
{
    set_uint16 ( ATT_CONNECT_IND_T_flags , value );
}

uint16 ATT_CONNECT_IND_T_PDU::get_mtu() const
{
    return get_uint16 ( ATT_CONNECT_IND_T_mtu );
}

void ATT_CONNECT_IND_T_PDU::set_mtu( uint16 value )
{
    set_uint16 ( ATT_CONNECT_IND_T_mtu , value );
}

uint16 ATT_CONNECT_IND_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_CONNECT_IND_T_cid );
}

void ATT_CONNECT_IND_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_CONNECT_IND_T_cid , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_READ_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_READ_REQ_T_PDU::ATT_READ_REQ_T_PDU()
: ATT_PDU ( ATT_READ_REQ , ATT_READ_REQ_T_pduSize )
{
}

ATT_READ_REQ_T_PDU::ATT_READ_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_READ_REQ_T_PDU::ATT_READ_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_READ_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_READ_REQ_T_phandle );
}

void ATT_READ_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_READ_REQ_T_phandle , value );
}

uint16 ATT_READ_REQ_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_READ_REQ_T_cid );
}

void ATT_READ_REQ_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_READ_REQ_T_cid , value );
}

uint16 ATT_READ_REQ_T_PDU::get_handle() const
{
    return get_uint16 ( ATT_READ_REQ_T_handle );
}

void ATT_READ_REQ_T_PDU::set_handle( uint16 value )
{
    set_uint16 ( ATT_READ_REQ_T_handle , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_EXECUTE_WRITE_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_EXECUTE_WRITE_CFM_T_PDU::ATT_EXECUTE_WRITE_CFM_T_PDU()
: ATT_PDU ( ATT_EXECUTE_WRITE_CFM , ATT_EXECUTE_WRITE_CFM_T_pduSize )
{
}

ATT_EXECUTE_WRITE_CFM_T_PDU::ATT_EXECUTE_WRITE_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_EXECUTE_WRITE_CFM_T_PDU::ATT_EXECUTE_WRITE_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_EXECUTE_WRITE_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_EXECUTE_WRITE_CFM_T_phandle );
}

void ATT_EXECUTE_WRITE_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_EXECUTE_WRITE_CFM_T_phandle , value );
}

uint16 ATT_EXECUTE_WRITE_CFM_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_EXECUTE_WRITE_CFM_T_cid );
}

void ATT_EXECUTE_WRITE_CFM_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_EXECUTE_WRITE_CFM_T_cid , value );
}

uint16 ATT_EXECUTE_WRITE_CFM_T_PDU::get_handle() const
{
    return get_uint16 ( ATT_EXECUTE_WRITE_CFM_T_handle );
}

void ATT_EXECUTE_WRITE_CFM_T_PDU::set_handle( uint16 value )
{
    set_uint16 ( ATT_EXECUTE_WRITE_CFM_T_handle , value );
}

uint16 ATT_EXECUTE_WRITE_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_EXECUTE_WRITE_CFM_T_result );
}

void ATT_EXECUTE_WRITE_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_EXECUTE_WRITE_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_HANDLE_VALUE_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_HANDLE_VALUE_CFM_T_PDU::ATT_HANDLE_VALUE_CFM_T_PDU()
: ATT_PDU ( ATT_HANDLE_VALUE_CFM , ATT_HANDLE_VALUE_CFM_T_pduSize )
{
}

ATT_HANDLE_VALUE_CFM_T_PDU::ATT_HANDLE_VALUE_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_HANDLE_VALUE_CFM_T_PDU::ATT_HANDLE_VALUE_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_HANDLE_VALUE_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_HANDLE_VALUE_CFM_T_phandle );
}

void ATT_HANDLE_VALUE_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_HANDLE_VALUE_CFM_T_phandle , value );
}

uint16 ATT_HANDLE_VALUE_CFM_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_HANDLE_VALUE_CFM_T_cid );
}

void ATT_HANDLE_VALUE_CFM_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_HANDLE_VALUE_CFM_T_cid , value );
}

uint16 ATT_HANDLE_VALUE_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_HANDLE_VALUE_CFM_T_result );
}

void ATT_HANDLE_VALUE_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_HANDLE_VALUE_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_CONNECT_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_CONNECT_REQ_T_PDU::ATT_CONNECT_REQ_T_PDU()
: ATT_PDU ( ATT_CONNECT_REQ , ATT_CONNECT_REQ_T_pduSize )
{
}

ATT_CONNECT_REQ_T_PDU::ATT_CONNECT_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_CONNECT_REQ_T_PDU::ATT_CONNECT_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_CONNECT_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_CONNECT_REQ_T_phandle );
}

void ATT_CONNECT_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_CONNECT_REQ_T_phandle , value );
}

BluetoothDeviceAddressWithType ATT_CONNECT_REQ_T_PDU::get_addrt() const
{
    return get_BluetoothDeviceAddressWithType ( ATT_CONNECT_REQ_T_addrt );
}

void ATT_CONNECT_REQ_T_PDU::set_addrt( BluetoothDeviceAddressWithType value )
{
    set_BluetoothDeviceAddressWithType ( ATT_CONNECT_REQ_T_addrt , value );
}

uint16 ATT_CONNECT_REQ_T_PDU::get_flags() const
{
    return get_uint16 ( ATT_CONNECT_REQ_T_flags );
}

void ATT_CONNECT_REQ_T_PDU::set_flags( uint16 value )
{
    set_uint16 ( ATT_CONNECT_REQ_T_flags , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_FIND_INFO_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_FIND_INFO_REQ_T_PDU::ATT_FIND_INFO_REQ_T_PDU()
: ATT_PDU ( ATT_FIND_INFO_REQ , ATT_FIND_INFO_REQ_T_pduSize )
{
}

ATT_FIND_INFO_REQ_T_PDU::ATT_FIND_INFO_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_FIND_INFO_REQ_T_PDU::ATT_FIND_INFO_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_FIND_INFO_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_FIND_INFO_REQ_T_phandle );
}

void ATT_FIND_INFO_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_FIND_INFO_REQ_T_phandle , value );
}

uint16 ATT_FIND_INFO_REQ_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_FIND_INFO_REQ_T_cid );
}

void ATT_FIND_INFO_REQ_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_FIND_INFO_REQ_T_cid , value );
}

uint16 ATT_FIND_INFO_REQ_T_PDU::get_start() const
{
    return get_uint16 ( ATT_FIND_INFO_REQ_T_start );
}

void ATT_FIND_INFO_REQ_T_PDU::set_start( uint16 value )
{
    set_uint16 ( ATT_FIND_INFO_REQ_T_start , value );
}

uint16 ATT_FIND_INFO_REQ_T_PDU::get_end() const
{
    return get_uint16 ( ATT_FIND_INFO_REQ_T_end );
}

void ATT_FIND_INFO_REQ_T_PDU::set_end( uint16 value )
{
    set_uint16 ( ATT_FIND_INFO_REQ_T_end , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_WRITE_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_WRITE_CFM_T_PDU::ATT_WRITE_CFM_T_PDU()
: ATT_PDU ( ATT_WRITE_CFM , ATT_WRITE_CFM_T_pduSize )
{
}

ATT_WRITE_CFM_T_PDU::ATT_WRITE_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_WRITE_CFM_T_PDU::ATT_WRITE_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_WRITE_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_WRITE_CFM_T_phandle );
}

void ATT_WRITE_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_WRITE_CFM_T_phandle , value );
}

uint16 ATT_WRITE_CFM_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_WRITE_CFM_T_cid );
}

void ATT_WRITE_CFM_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_WRITE_CFM_T_cid , value );
}

uint16 ATT_WRITE_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_WRITE_CFM_T_result );
}

void ATT_WRITE_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_WRITE_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_ADD_DB_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_ADD_DB_CFM_T_PDU::ATT_ADD_DB_CFM_T_PDU()
: ATT_PDU ( ATT_ADD_DB_CFM , ATT_ADD_DB_CFM_T_pduSize )
{
}

ATT_ADD_DB_CFM_T_PDU::ATT_ADD_DB_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_ADD_DB_CFM_T_PDU::ATT_ADD_DB_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_ADD_DB_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_ADD_DB_CFM_T_phandle );
}

void ATT_ADD_DB_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_ADD_DB_CFM_T_phandle , value );
}

uint16 ATT_ADD_DB_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_ADD_DB_CFM_T_result );
}

void ATT_ADD_DB_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_ADD_DB_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_EXCHANGE_MTU_CFM_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_EXCHANGE_MTU_CFM_T_PDU::ATT_EXCHANGE_MTU_CFM_T_PDU()
: ATT_PDU ( ATT_EXCHANGE_MTU_CFM , ATT_EXCHANGE_MTU_CFM_T_pduSize )
{
}

ATT_EXCHANGE_MTU_CFM_T_PDU::ATT_EXCHANGE_MTU_CFM_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_EXCHANGE_MTU_CFM_T_PDU::ATT_EXCHANGE_MTU_CFM_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_EXCHANGE_MTU_CFM_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_CFM_T_phandle );
}

void ATT_EXCHANGE_MTU_CFM_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_CFM_T_phandle , value );
}

uint16 ATT_EXCHANGE_MTU_CFM_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_CFM_T_cid );
}

void ATT_EXCHANGE_MTU_CFM_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_CFM_T_cid , value );
}

uint16 ATT_EXCHANGE_MTU_CFM_T_PDU::get_mtu() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_CFM_T_mtu );
}

void ATT_EXCHANGE_MTU_CFM_T_PDU::set_mtu( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_CFM_T_mtu , value );
}

uint16 ATT_EXCHANGE_MTU_CFM_T_PDU::get_result() const
{
    return get_uint16 ( ATT_EXCHANGE_MTU_CFM_T_result );
}

void ATT_EXCHANGE_MTU_CFM_T_PDU::set_result( uint16 value )
{
    set_uint16 ( ATT_EXCHANGE_MTU_CFM_T_result , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_UNREGISTER_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_UNREGISTER_REQ_T_PDU::ATT_UNREGISTER_REQ_T_PDU()
: ATT_PDU ( ATT_UNREGISTER_REQ , ATT_UNREGISTER_REQ_T_pduSize )
{
}

ATT_UNREGISTER_REQ_T_PDU::ATT_UNREGISTER_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_UNREGISTER_REQ_T_PDU::ATT_UNREGISTER_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_UNREGISTER_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_UNREGISTER_REQ_T_phandle );
}

void ATT_UNREGISTER_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_UNREGISTER_REQ_T_phandle , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_HANDLE_VALUE_RSP_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_HANDLE_VALUE_RSP_T_PDU::ATT_HANDLE_VALUE_RSP_T_PDU()
: ATT_PDU ( ATT_HANDLE_VALUE_RSP , ATT_HANDLE_VALUE_RSP_T_pduSize )
{
}

ATT_HANDLE_VALUE_RSP_T_PDU::ATT_HANDLE_VALUE_RSP_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_HANDLE_VALUE_RSP_T_PDU::ATT_HANDLE_VALUE_RSP_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_HANDLE_VALUE_RSP_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_HANDLE_VALUE_RSP_T_phandle );
}

void ATT_HANDLE_VALUE_RSP_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_HANDLE_VALUE_RSP_T_phandle , value );
}

uint16 ATT_HANDLE_VALUE_RSP_T_PDU::get_cid() const
{
    return get_uint16 ( ATT_HANDLE_VALUE_RSP_T_cid );
}

void ATT_HANDLE_VALUE_RSP_T_PDU::set_cid( uint16 value )
{
    set_uint16 ( ATT_HANDLE_VALUE_RSP_T_cid , value );
}

///////////////////////////////////////////////////////////////////////////////
//
//  Class: ATT_REGISTER_REQ_T_PDU
//
///////////////////////////////////////////////////////////////////////////////

ATT_REGISTER_REQ_T_PDU::ATT_REGISTER_REQ_T_PDU()
: ATT_PDU ( ATT_REGISTER_REQ , ATT_REGISTER_REQ_T_pduSize )
{
}

ATT_REGISTER_REQ_T_PDU::ATT_REGISTER_REQ_T_PDU( const PDU& from )
: ATT_PDU ( from )
{
}

ATT_REGISTER_REQ_T_PDU::ATT_REGISTER_REQ_T_PDU( const uint8 * buffer , uint32 len )
: ATT_PDU ( buffer , len )
{
}

uint16 ATT_REGISTER_REQ_T_PDU::get_phandle() const
{
    return get_uint16 ( ATT_REGISTER_REQ_T_phandle );
}

void ATT_REGISTER_REQ_T_PDU::set_phandle( uint16 value )
{
    set_uint16 ( ATT_REGISTER_REQ_T_phandle , value );
}

