////////////////////////////////////////////////////////////////////////////////
//
//  WARNING THIS IS AN AUTOGENERATED FILE from hci_dm_xtra.tpl
//
////////////////////////////////////////////////////////////////////////////////

#include "hcipacker/gen_xtrahcicommand.h"
#include "common/types_t.h"
#include "app/bluestack/bluetooth.h"
#include "app/bluestack/hci.h"
#include "hcilayout.h"



#define OFFSET_START(name) 

enum {
    OFFSET_START(HCI_SET_EVENT_MASK_T_PDU)
    OFFSET_uint16(HCI_SET_EVENT_MASK_T_op_code),
    OFFSET_uint8(HCI_SET_EVENT_MASK_T_length),
    OFFSET_EventMask(HCI_SET_EVENT_MASK_T_event_mask),
    HCI_SET_EVENT_MASK_T_pduSize
} ;

HCI_SET_EVENT_MASK_T_PDU::HCI_SET_EVENT_MASK_T_PDU()
: HCICommandPDU(HCI_SET_EVENT_MASK,HCI_SET_EVENT_MASK_T_pduSize)
{
}

HCI_SET_EVENT_MASK_T_PDU::HCI_SET_EVENT_MASK_T_PDU( const PDU& from )
: HCICommandPDU(from)
{
}

HCI_SET_EVENT_MASK_T_PDU::HCI_SET_EVENT_MASK_T_PDU( const uint8 * data , uint32 size )
: HCICommandPDU(data,size)
{
}

const HCIEventMask HCI_SET_EVENT_MASK_T_PDU::get_event_mask() const
{
    uint8 mask[8];
    // byte spaced on both HCI and DM
    PDU::get_uint8Array ( mask , HCI_SET_EVENT_MASK_T_event_mask , 8 );
    return HCIEventMask ( mask );
}

void HCI_SET_EVENT_MASK_T_PDU::set_event_mask ( const HCIEventMask& mask )
{
    // byte spaced on both HCI and DM
    PDU::set_uint8Array ( mask.get_data() , HCI_SET_EVENT_MASK_T_event_mask , 8 ) ;
}


enum {
    OFFSET_START(HCI_WRITE_CURRENT_IAC_LAP_T_PDU)
    OFFSET_uint16(HCI_WRITE_CURRENT_IAC_LAP_T_op_code),
    OFFSET_uint8(HCI_WRITE_CURRENT_IAC_LAP_T_length),
    OFFSET_uint8(HCI_WRITE_CURRENT_IAC_LAP_T_num_current_iac),
    OFFSET_PtrArray(DM_HCI_WRITE_CURRENT_IAC_LAP_T_iac_lap,HCI_IAC_LAP_PTRS),
    DM_HCI_WRITE_CURRENT_IAC_LAP_T_pduSize,
    HCI_WRITE_CURRENT_IAC_LAP_T_pduSize = DM_HCI_WRITE_CURRENT_IAC_LAP_T_iac_lap
} ;

HCI_WRITE_CURRENT_IAC_LAP_T_PDU::HCI_WRITE_CURRENT_IAC_LAP_T_PDU()
: HCICommandPDU(HCI_WRITE_CURRENT_IAC_LAP,HCI_WRITE_CURRENT_IAC_LAP_T_pduSize)
{
}

HCI_WRITE_CURRENT_IAC_LAP_T_PDU::HCI_WRITE_CURRENT_IAC_LAP_T_PDU( const PDU& from )
: HCICommandPDU(from)
{
}

HCI_WRITE_CURRENT_IAC_LAP_T_PDU::HCI_WRITE_CURRENT_IAC_LAP_T_PDU( const uint8 * data , uint32 size )
: HCICommandPDU(data,size)
{
}

uint8 HCI_WRITE_CURRENT_IAC_LAP_T_PDU::get_num_current_iac(void) const
{
    return get_uint8(HCI_WRITE_CURRENT_IAC_LAP_T_num_current_iac) ;
}

void HCI_WRITE_CURRENT_IAC_LAP_T_PDU::set_num_current_iac(uint8 val)
{
    set_uint8(HCI_WRITE_CURRENT_IAC_LAP_T_num_current_iac,val) ;
}

uint24 HCI_WRITE_CURRENT_IAC_LAP_T_PDU::get_iac_lap(uint8 index) const
{
    return get_uint24(HCI_WRITE_CURRENT_IAC_LAP_T_pduSize + index*3) ;
}

void HCI_WRITE_CURRENT_IAC_LAP_T_PDU::set_iac_lap(uint8 index,uint24 val)
{
    uint16 required_length = HCI_WRITE_CURRENT_IAC_LAP_T_pduSize + (index+1) *3;
    if (size() < required_length) 
    {
        resize (required_length) ;
    }
    set_uint24(required_length-3,val) ;
    if (index >= get_num_current_iac()) set_num_current_iac(index+1) ; 
}



enum {
    OFFSET_START(HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU)
    OFFSET_uint16(HCI_HOST_NUM_COMPLETED_PACKETS_T_op_code),
    OFFSET_uint8(HCI_HOST_NUM_COMPLETED_PACKETS_T_length),
    OFFSET_uint8(HCI_HOST_NUM_COMPLETED_PACKETS_T_num_handles),
    HCI_HOST_NUM_COMPLETED_PACKETS_T_pduSize
} ;




HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU::HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU()
: HCICommandPDU(HCI_HOST_NUM_COMPLETED_PACKETS,HCI_HOST_NUM_COMPLETED_PACKETS_T_pduSize)
{
}

HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU::HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU( const PDU& from )
: HCICommandPDU(from)
{
}

HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU::HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU( const uint8 * data , uint32 size )
: HCICommandPDU(data,size)
{
}

uint8 HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU::get_num_handles(void) const
{
    return get_uint8(HCI_HOST_NUM_COMPLETED_PACKETS_T_num_handles) ;
}

void HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU::set_num_handles(uint8 val)
{
    resize(HCI_HOST_NUM_COMPLETED_PACKETS_T_pduSize + val * 4);
    set_uint8(HCI_HOST_NUM_COMPLETED_PACKETS_T_num_handles,val) ;
}

void HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU::get_num_completed_pkts(uint8 index,uint16 &handle,uint16 &pkts ) const
{
    uint16 offset = HCI_HOST_NUM_COMPLETED_PACKETS_T_pduSize;
    offset += index *(2+2) ;
    handle = get_uint16(offset) ; offset +=2 ;
    pkts = get_uint16(offset) ;         
}

void HCI_HOST_NUM_COMPLETED_PACKETS_T_PDU::set_num_completed_pkts(uint8 index,uint16 handle,uint16 pkts )
{
    if (index>= get_num_handles()) 
    {
        //TODO - throw an exception 
    }

    uint16 offset = HCI_HOST_NUM_COMPLETED_PACKETS_T_pduSize;
    offset += index *(2+2) ;
    set_uint16(offset,handle) ; offset +=2 ;
    set_uint16(offset,pkts) ;           
}

enum {
    OFFSET_START(HCI_WRITE_STORED_LINK_KEY_T)
    OFFSET_uint16(HCI_WRITE_STORED_LINK_KEY_T_op_code),
    OFFSET_uint8(HCI_WRITE_STORED_LINK_KEY_T_length),
    OFFSET_uint8(HCI_WRITE_STORED_LINK_KEY_T_number_keys),
    OFFSET_PtrArray(DM_HCI_WRITE_STORED_LINK_KEY_T_link_key_bd_addr,HCI_STORED_LINK_KEY_MAX),
    DM_HCI_WRITE_STORED_LINK_KEY_T_pduSize,
    HCI_WRITE_STORED_LINK_KEY_T_pduSize = DM_HCI_WRITE_STORED_LINK_KEY_T_link_key_bd_addr
} ;

HCI_WRITE_STORED_LINK_KEY_T_PDU::HCI_WRITE_STORED_LINK_KEY_T_PDU()
: HCICommandPDU(HCI_WRITE_STORED_LINK_KEY,HCI_WRITE_STORED_LINK_KEY_T_pduSize)
{
}

HCI_WRITE_STORED_LINK_KEY_T_PDU::HCI_WRITE_STORED_LINK_KEY_T_PDU( const PDU& from )
: HCICommandPDU(from)
{
}

HCI_WRITE_STORED_LINK_KEY_T_PDU::HCI_WRITE_STORED_LINK_KEY_T_PDU( const uint8 * data , uint32 size )
: HCICommandPDU(data,size)
{
}

uint8 HCI_WRITE_STORED_LINK_KEY_T_PDU::get_number_keys(void) const
{
    return get_uint8(HCI_WRITE_STORED_LINK_KEY_T_number_keys) ;
}

void HCI_WRITE_STORED_LINK_KEY_T_PDU::set_number_keys(uint8 val)
{
    //  HCI bdaddr size = 6, link key size = 16
    resize ( HCI_WRITE_STORED_LINK_KEY_T_pduSize + val * (6+16) );
    set_uint8(HCI_WRITE_STORED_LINK_KEY_T_number_keys,val) ;
}

void HCI_WRITE_STORED_LINK_KEY_T_PDU::get_link_key_bd_addr ( uint8 index , BluetoothDeviceAddress &addr , LinkKey &key ) const
{
    if (HCI_WRITE_STORED_LINK_KEY_T_pduSize + index * (6 + 16) + 6 + 16 > size())
    {
        return;
    }
    uint16 offset = HCI_WRITE_STORED_LINK_KEY_T_pduSize ;
    offset += index * (6+16) ; //6 = bdaddr size, 16 = link key size
    addr = get_BluetoothDeviceAddress(offset) ;
    offset+=6 ;
    uint8 lKey[16];
    get_uint8Array( lKey , offset , 16 );
    LinkKey k(lKey) ;
    key = k ;
}

void HCI_WRITE_STORED_LINK_KEY_T_PDU::set_link_key_bd_addr ( uint8 index , const BluetoothDeviceAddress& addr , const LinkKey& key )
{
    if (HCI_WRITE_STORED_LINK_KEY_T_pduSize + index * (6 + 16) + 6 + 16 > size())
    {
        return;
    }
    uint16 offset = HCI_WRITE_STORED_LINK_KEY_T_pduSize ;
    offset += index * (6+16) ; //6 = bdaddr size, 16 = link key size
    set_BluetoothDeviceAddress(offset,addr) ;
    offset+=6 ;
    // byte spaced on HCI, word spaced on DM
    set_uint8Array(key.get_data(),offset,16) ;
}

/*******************************************************************/

enum {
    OFFSET_START(HCI_SET_EVENT_FILTER_T)
    OFFSET_uint16(HCI_SET_EVENT_FILTER_T_op_code),
    OFFSET_uint8(HCI_SET_EVENT_FILTER_T_length),
    OFFSET_uint8(HCI_SET_EVENT_FILTER_T_filter_type),
    OFFSET_uint8(HCI_SET_EVENT_FILTER_T_filter_condition_type),
    OFFSET_uint24(HCI_SET_EVENT_FILTER_T_COD),
    OFFSET_uint24(HCI_SET_EVENT_FILTER_T_COD_mask),
    OFFSET_uint8(HCI_SET_EVENT_FILTER_T_AAF_COD),
    DM_HCI_SET_EVENT_FILTER_T_pduSize,
    HCI_SET_EVENT_FILTER_T_pduSize = HCI_SET_EVENT_FILTER_T_filter_condition_type,
    HCI_SET_EVENT_FILTER_T_BDA = HCI_SET_EVENT_FILTER_T_COD,
    HCI_SET_EVENT_FILTER_T_AAF_all = HCI_SET_EVENT_FILTER_T_COD,
    HCI_SET_EVENT_FILTER_T_AAF_BDA = HCI_SET_EVENT_FILTER_T_AAF_COD
} ;

HCI_SET_EVENT_FILTER_T_PDU::HCI_SET_EVENT_FILTER_T_PDU()
:   HCICommandPDU ( HCI_SET_EVENT_FILTER , HCI_SET_EVENT_FILTER_T_pduSize )
{
}

HCI_SET_EVENT_FILTER_T_PDU::HCI_SET_EVENT_FILTER_T_PDU( const PDU& from )
:   HCICommandPDU ( from )
{
}

HCI_SET_EVENT_FILTER_T_PDU::HCI_SET_EVENT_FILTER_T_PDU( const uint8* buffer , uint32 len )
:   HCICommandPDU ( buffer , len )
{
}

uint8 HCI_SET_EVENT_FILTER_T_PDU::get_filter_type() const
{
    return get_uint8 ( HCI_SET_EVENT_FILTER_T_filter_type );
}

uint8 HCI_SET_EVENT_FILTER_T_PDU::get_filter_condition_type() const
{
    if ( size() > HCI_SET_EVENT_FILTER_T_filter_condition_type )
        return get_uint8 ( HCI_SET_EVENT_FILTER_T_filter_condition_type );
    else
        return 0xFF;
}

void HCI_SET_EVENT_FILTER_T_PDU::set_filter_type ( uint8 type )
{
    if ( type == 0 )
        resize ( HCI_SET_EVENT_FILTER_T_filter_condition_type );
    set_uint8 ( HCI_SET_EVENT_FILTER_T_filter_type , type );
}

////////////////////////////////
//  FT  FCT   len
////////////////////////////////
//  0    -     4  (3+1)
//  1    0     5  (3+1+1)
//  1    1     11 (3+1+1+3+3)
//  1    2     11 (3+1+1+6)
//  2    0     6  (3+1+1+1)
//  2    1     12 (3+1+1+1+3+3)
//  2    2     12 (3+1+1+1+6)
////////////////////////////////

void HCI_SET_EVENT_FILTER_T_PDU::set_filter_condition_type ( uint8 type )
{
    uint8 ft = get_filter_type();
    uint16 size = 4; // basic, 3 header + 1 FT
    switch ( ft )
    {
    case 0:
        return;
    case 1: //  must have FCT.
        size++;
        break;
    case 2: //  must have FCT and AAF
        size += 2;
        break;
    default:
        return;
    }
    switch ( type )
    {
    case 0: //  nothing
        break;
    case 1: //  COD and COD mask
        size += 6;
        break;
    case 2: //  BDA
        size += 6;
        break;
    default:
        return;
    }
    resize ( size );
    set_uint8 ( HCI_SET_EVENT_FILTER_T_filter_condition_type , type );
}

bool HCI_SET_EVENT_FILTER_T_PDU::get_condition ( BluetoothDeviceAddress& bda ) const
{
    if ( get_filter_type() && ( get_filter_condition_type() == 2 ) )
    {
        bda = get_BluetoothDeviceAddress( HCI_SET_EVENT_FILTER_T_BDA );
        return true;
    }
    return false;
}

bool HCI_SET_EVENT_FILTER_T_PDU::get_condition ( ClassOfDevice& val, ClassOfDevice& mask ) const
{
    if ( get_filter_type() && ( get_filter_condition_type() == 1 ) )
    {
        val  = get_ClassOfDevice ( HCI_SET_EVENT_FILTER_T_COD );
        mask = get_ClassOfDevice ( HCI_SET_EVENT_FILTER_T_COD_mask );
        return true;
    }
    return false;
}

bool HCI_SET_EVENT_FILTER_T_PDU::get_condition ( uint8& auto_accept_flag ) const
{
    bool ok = (get_filter_type() == 2);
    if ( ok )
    {
        switch ( get_filter_condition_type() )
        {
        case 0:
            auto_accept_flag = get_uint8(HCI_SET_EVENT_FILTER_T_AAF_all );
            break;
        case 1:
            auto_accept_flag = get_uint8(HCI_SET_EVENT_FILTER_T_AAF_COD );
            break;
        case 2:
            auto_accept_flag = get_uint8(HCI_SET_EVENT_FILTER_T_AAF_BDA );
            break;
        default:
            ok = false;
            break;
        }
    }
    return ok;
}

bool HCI_SET_EVENT_FILTER_T_PDU::set_condition ( const BluetoothDeviceAddress& bda )
{
    if ( get_filter_type() && ( get_filter_condition_type() == 2 ) )
    {
        set_BluetoothDeviceAddress( HCI_SET_EVENT_FILTER_T_BDA , bda );
        return true;
    }
    return false;
}

bool HCI_SET_EVENT_FILTER_T_PDU::set_condition ( const ClassOfDevice& val, const ClassOfDevice& mask )
{
    uint8 ft = get_filter_type();
    if ( ft && ( get_filter_condition_type() == 1 ) )
    {
        set_ClassOfDevice ( HCI_SET_EVENT_FILTER_T_COD , val );
        set_ClassOfDevice ( HCI_SET_EVENT_FILTER_T_COD_mask , mask );
        return true;
    }
    return false;
}

bool HCI_SET_EVENT_FILTER_T_PDU::set_condition ( uint8 auto_accept_flag )
{
    bool ok = (get_filter_type() == 2);
    if ( ok )
    {
        switch ( get_filter_condition_type() )
        {
        case 0:
            set_uint8 ( HCI_SET_EVENT_FILTER_T_AAF_all , auto_accept_flag );
            break;
        case 1:
            set_uint8 ( HCI_SET_EVENT_FILTER_T_AAF_COD , auto_accept_flag );
            break;
        case 2:
            set_uint8 ( HCI_SET_EVENT_FILTER_T_AAF_BDA , auto_accept_flag );
            break;
        default:
            ok = false;
            break;
        }
    }
    return ok;
}

